### ISSUE TITLE
TypeError: Cannot read property 'some' of undefined

### ISSUE THREAD

**Issue by buriable** [plorry/VegAssist#2] opened 2015-10-23 01:35 UTC
I couldn't get this to work, sadly...

TypeError: Cannot read property 'some' of undefined
    at tweetContainsFilteredTerms (/Users/Jarvis/Documents/Git/cocaine/vegassist.js:27:44)
    at inspectTweet (/Users/Jarvis/Documents/Git/cocaine/vegassist.js:33:32)
    at null.<anonymous> (/Users/Jarvis/Documents/Git/cocaine/vegassist.js:58:5)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at null.<anonymous> (/Users/Jarvis/Documents/Git/cocaine/node_modules/twit/lib/streaming-api-connection.js:294:56)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at Parser.parse (/Users/Jarvis/Documents/Git/cocaine/node_modules/twit/lib/parser.js:41:16)
    at IncomingMessage.<anonymous> (/Users/Jarvis/Documents/Git/cocaine/node_modules/twit/lib/streaming-api-connection.js:115:19)

**Comment by squeek502** [comment] 2015-10-23 01:51
Related to [this comment](https://github.com/plorry/VegAssist/commit/c3806b83da9e3fd683b7b20757ef2e89581bf74a#commitcomment-13935152). The problem is that a `FILTERED_TERMS` key is expected in `settings.js`. Should be fixed soon.

**Closed as completed** 2015-10-23 17:27 UTC
